<a href="https://www.kaggle.com/code/hanpat99/singular-matrix-check?scriptVersionId=116622877" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

This code checks whether a **4 x 4 matrix** is *singular.*

Matrix singularity becomes important when theres a need to check for **dimensionality** of dataframes.

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


# Our function will go through the matrix replacing each row in order turning it into echelon form.
# If at any point it fails because it can't put a 1 in the leading diagonal,
# we will return the value True, otherwise, we will return False.
# There is no need to edit this function.
def isSingular(A) :
    B = np.array(A, dtype=np.float_) # Make B as a copy of A, since we're going to alter it's values.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# This next line defines our error flag. For when things go wrong if the matrix is singular.
# There is no need to edit this line.
class MatrixIsSingular(Exception): pass

# For Row Zero, all we require is the first element is equal to 1.
# We'll divide the row by the value of A[0, 0].
# This will get us in trouble though if A[0, 0] equals 0, so first we'll test for that,
# and if this is true, we'll add one of the lower rows to the first one before the division.
# We'll repeat the test going down each lower row until we can do the division.
# There is no need to edit this function.
def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
        print('round 1:', A[0])
        
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
        print('round 2:', A[0])
        
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
        print('round 3:', A[0])
        
    if A[0,0] == 0 :
        raise MatrixIsSingular()
        
    A[0] = A[0] / A[0,0] #divides the whole row by element A[0,0], and sets A[0,0] to 1
    print('round 4:', A[0])
    
    print(A)
    return

# First we'll set the sub-diagonal elements to zero, i.e. A[1,0].
# Next we want the diagonal element to be equal to one.
# We'll divide the row by the value of A[1, 1].
# Again, we need to test if this is zero.
# If so, we'll add a lower row and repeat setting the sub-diagonal elements to zero.
# There is no need to edit this function.
def fixRowOne(A) :   
    A[1] = A[1] - A[1,0] * A[0] #A[0,0] has been set to 1 previously. This line sets A[1,0] to zero.
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        print('round 5:', A[1])
        
        A[1] = A[1] - A[1,0] * A[0]
        print('round 7:', A[1])
        
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        print('round 8:', A[1])
        
        A[1] = A[1] - A[1,0] * A[0]
        print('round 9:', A[1])
        
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    print('round 10:', A[1])
    
    print(A)
    return

# This is the first function that you should complete.
# Follow the instructions inside the function at each comment.
def fixRowTwo(A) :
    # Insert code below to set the sub-diagonal elements of row two to zero (there are two of them).
    A[2] = A[2] - A[2, 0] * A[0]
    print('round 11:', A[2])
    
    A[2] = A[2] - A[2, 1] * A[1]
    print('round 12:', A[2])
    
    # Next we'll test that the diagonal element is not zero.
    if A[2,2] == 0 :
        # Insert code below that adds a lower row to row 2.
        A[2] = A[2] + A[3]
        print('round 13:', A[2])
        
        A[2] = A[2] - A[2,0]*A[0]
        print('round 14:', A[2])
        
        # Now repeat your code which sets the sub-diagonal elements to zero.
        A[2] = A[2] - A[2,1]*A[1]
        print('round 15:', A[2])
       
        
    if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Finally set the diagonal element to one by dividing the whole row by that element.
    A[2] =  A[2] / A[2, 2]
    print('round 16:', A[2])
    
    print(A)
    return

# You should also complete this function
# Follow the instructions inside the function at each comment.
def fixRowThree(A) :
    # Insert code below to set the sub-diagonal elements of row three to zero.
    A[3] = A[3] - A[3,0]*A[0]
    print('round 17:', A[3])
    
    A[3] = A[3] - A[3,1]*A[1]
    print('round 18:', A[3])
    
    A[3] = A[3] - A[3,2]*A[2]
    print('round 19:', A[3])
    
    # Complete the if statement to test if the diagonal element is zero.
    if A[3,3] == 0:
        raise MatrixIsSingular()
    # Transform the row to set the diagonal element to one.
    A[3] = A[3] / A[3, 3]
    print('round 20:', A[3])
    
    print(A)
    return

In [2]:
B = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(B)

round 4: [1. 0. 0. 0.]
[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
round 10: [0. 1. 0. 0.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 4. 4.]
 [0. 0. 5. 5.]]
round 11: [0. 0. 4. 4.]
round 12: [0. 0. 4. 4.]
round 16: [0. 0. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 5. 5.]]
round 17: [0. 0. 5. 5.]
round 18: [0. 0. 5. 5.]
round 19: [0. 0. 0. 0.]


True

In [3]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)



round 1: [ 2. 15. -5.  7.]
round 4: [ 1.   7.5 -2.5  3.5]
[[ 1.   7.5 -2.5  3.5]
 [ 2.   8.   0.   4. ]
 [ 3.  12.   0.   5. ]
 [ 1.   3.   1.   3. ]]


In [4]:
isSingular(A)

round 4: [ 1.   7.5 -2.5  3.5]
[[ 1.   7.5 -2.5  3.5]
 [ 2.   8.   0.   4. ]
 [ 3.  12.   0.   5. ]
 [ 1.   3.   1.   3. ]]
round 10: [-0.          1.         -0.71428571  0.42857143]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 3.         12.          0.          5.        ]
 [ 1.          3.          1.          3.        ]]
round 11: [  0.  -10.5   7.5  -5.5]
round 12: [ 0.  0.  0. -1.]
round 13: [1. 3. 1. 2.]
round 14: [ 0.  -4.5  3.5 -1.5]
round 15: [0.         0.         0.28571429 0.42857143]
round 16: [0.  0.  1.  1.5]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 0.          0.          1.          1.5       ]
 [ 1.          3.          1.          3.        ]]
round 17: [ 0.  -4.5  3.5 -0.5]
round 18: [0.         0.         0.28571429 1.42857143]
round 19: [0. 0. 0. 1.]
round 20: [0. 0. 0. 1.]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          

False

In [5]:
fixRowTwo(A)

round 11: [  0.  -10.5   7.5  -5.5]
round 12: [21.  73.5  7.5 36.5]
round 16: [2.8        9.8        1.         4.86666667]
[[ 1.          7.5        -2.5         3.5       ]
 [ 2.          8.          0.          4.        ]
 [ 2.8         9.8         1.          4.86666667]
 [ 1.          3.          1.          3.        ]]


In [6]:
fixRowOne(A)

round 10: [-0.          1.         -0.71428571  0.42857143]
[[ 1.          7.5        -2.5         3.5       ]
 [-0.          1.         -0.71428571  0.42857143]
 [ 2.8         9.8         1.          4.86666667]
 [ 1.          3.          1.          3.        ]]
